name: fast_render
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch==2.0.1
  - torchvision==0.15.2
  - torchaudio==2.0.2
  - pytorch-cuda=11.8
  - pip:
    - open3d
    - plyfile
    - ninja
    - GPUtil
    - opencv-python
    - lpips
    - trimesh
    - pymeshlab
    - termcolor
    - wandb
    - imageio
    - scikit-image
    - torchmetrics
    - mediapy
    - "git+https://github.com/facebookresearch/pytorch3d.git"
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn